version: '3.8'

services:
  blog-api:
    build: .
    container_name: simple-blog-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service with auto-reload
  blog-api-dev:
    build: .
    container_name: simple-blog-api-dev
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - .:/app
    profiles:
      - dev
