services:
  blog-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: simple-blog-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - blog_data:/app/data
    restart: unless-stopped

  # Development service with auto-reload
  blog-api-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: simple-blog-api-dev
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ..:/app
      - blog_data:/app/data
    profiles:
      - dev

volumes:
  blog_data:
    driver: local
